name: "Build legacy Nix package on Ubuntu"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/*.nix', '**/Cargo.lock') }}
      - name: Checking formatting
        run: nix develop -c cargo fmt --check
      - name: Linting
        run: nix develop -c cargo clippy --all-targets -- -D warnings
      - name: Building package
        run: nix build
        